version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch

    steps:
      - add_ssh_keys:
          fingerprints:
            - "7c:9c:4e:70:48:2b:77:05:40:d5:2a:8b:9d:e9:d8:76"

      - checkout

      - run:
          name: LS
          command: pwd && ls -la

      - run:
          name: Install deps and fix bugs
          command: .circleci/pre_install.sh

      - run:
          name: Validate codestyle via foodcritic
          command: bundle exec foodcritic .

      - run:
          name: Validate codestyle via rubocop
          command: bundle exec rubocop .

      - run:
          name: Run testkitchen
          command: KITCHEN_LOCAL_YAML=.kitchen.ec2.yml bundle exec kitchen test
      #
      # - run:
      #     name: Upload to supermarket
      #     command: bundle exec knife cookbook site share chef-mdadm "Operating Systems & Virtualization"
